# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8a1206874082849c2443b9380087b8c5"
name = "etsapp1"
handle = "etsapp1"
application_url = "https://huydev.deskbox.org/etsapp1/dev/"
embedded = true

[build]
dev_store_url = "hydroshop998.myshopify.com"
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://huydev.deskbox.org/etsapp1/api/shopify/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
